package flightSearchserice.service.Entity;



import java.time.LocalDate;

import lombok.Builder;
import lombok.Data;


@Builder

public record Flight(
         Long id,
        String flightNumber,
        String origin,
        String destination,
        LocalDate departureDate,
        LocalDate arrivalDate,
        double amount,
        int totalSeats,
        int availableSeats) {

    // The withAvailableSeats method is automatically generated by the record
    public Flight withAvailableSeats(int newAvailableSeats) {
        return new Flight(
                id, flightNumber, origin, destination, departureDate,
                arrivalDate, amount, totalSeats, newAvailableSeats
        );
    }
}